Models/Enums/Currency.cs
namespace MyCourse.Models.Enums
{
    public enum Currency
    {
        EUR,
        USD,
        GBP
    }
}

Models/Services/Application/CorsiService.cs
using System;
using System.Collections.Generic;
using MyCourse.Models.Enums;
using MyCourse.Models.ValueTypes;
using MyCourse.Models.ViewModels;

namespace MyCourse.Models.Services.Application
{
    public class CorsiService : ICorsiService
    {
        public List<CorsiViewModel> GetCorsi()
        {
            var courseList = new List<CorsiViewModel>();
            var rand = new Random();
            for (int i = 1; i <= 20; i++)
            {
                var price = Convert.ToDecimal(rand.NextDouble() * 10 + 10);
                var course = new CorsiViewModel
                {
                    Id = i,
                    Title = $"Corso {i}",
                    CurrentPrice = new Money(Currency.EUR, price),
                    FullPrice = new Money(Currency.EUR, rand.NextDouble() > 0.5 ? price : price - 1),
                    Author = "Nome cognome",
                    Rating = rand.Next(10, 50) / 10.0,
                    ImagePath = "/logo.svg"
                };
                courseList.Add(course);
            }
            return courseList;
        }

        public CorsiDetailViewModel GetCorso(int id)
        {
            var rand = new Random();
            var price = Convert.ToDecimal(rand.NextDouble() * 10 + 10);
            var course = new CorsiDetailViewModel
            {
                Id = id,
                Title = $"Corso {id}",
                CurrentPrice = new Money(Currency.EUR, price),
                FullPrice = new Money(Currency.EUR, rand.NextDouble() > 0.5 ? price : price - 1),
                Author = "Nome cognome",
                Rating = rand.Next(10, 50) / 10.0,
                ImagePath = "/logo.svg",
                Description = $"Descrizione {id}",
                Lessons = new List<LessonViewModel>()
            };

            for (var i = 1; i <= 5; i++) {
                var lesson = new LessonViewModel {
                    Title = $"Lezione {i}",
                    Duration = TimeSpan.FromSeconds(rand.Next(40, 90))
                };
                course.Lessons.Add(lesson);
            }

            return course;
        }
    }
}

Models/Services/Application/ICorsiService.cs
using System.Collections.Generic;
using MyCourse.Models.ViewModels;

namespace MyCourse.Models.Services.Application
{
    public interface ICorsiService
    {
         List<CorsiViewModel> GetCorsi();

         CorsiDetailViewModel GetCorso(int id);
    }
}

Models/ValueTypes/Money.cs
using System;
using MyCourse.Models.Enums;

namespace MyCourse.Models.ValueTypes
{
    public class Money
    {
        public Money() : this(Currency.EUR, 0.00m)
        {
        }
        public Money(Currency currency, decimal amount)
        {
            Amount = amount;
            Currency = currency;
        }
        private decimal amount = 0;
        public decimal Amount
        { 
            get
            {
                return amount;
            }
            set
            {
                if (value < 0) {
                    throw new InvalidOperationException("The amount cannot be negative");
                }
                amount = value;
            }
        }
        public Currency Currency
        {
            get; set;
        }

        public override bool Equals(object obj)
        {
            var money = obj as Money;
            return money != null &&
                   Amount == money.Amount &&
                   Currency == money.Currency;
        }

        public override int GetHashCode()
        {
            return HashCode.Combine(Amount, Currency);
        }
        
        public override string ToString()
        {
            return $"{Currency} {Amount:#.00}";
        }
    }
}

Models/ViewModels/CorsiDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyCourse.Models.ViewModels
{
    public class CorsiDetailViewModel : CorsiViewModel
    {
        public string Description { get; set; }
        public List<LessonViewModel> Lessons { get; set; }

        
        public TimeSpan TotalCourseDuration
        {
            get => TimeSpan.FromSeconds(Lessons?.Sum(l => l.Duration.TotalSeconds) ?? 0);
        }
    }
}

Models/ViewModels/CorsiViewModel.cs
using MyCourse.Models.ValueTypes;

namespace MyCourse.Models.ViewModels
{
    public class CorsiViewModel
    {
        public int Id { get; set;}

        public string Title {get; set;}

        public string ImagePath {get; set;}

        public string Author {get; set;}

        public double Rating {get; set;}

        public Money FullPrice {get; set;}

        public Money CurrentPrice {get; set;}
    }
}

Models/ViewModels/LessonViewModel.cs
using System;

namespace MyCourse.Models.ViewModels
{
    public class LessonViewModel
    {
        public string Title { get; set; }

        public TimeSpan Duration { get; set; }
    }
}

Controllers/CorsiController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MyCourse.Models.Services.Application;
using MyCourse.Models.ViewModels;

namespace MyCourse.Controllers
{
    public class CorsiController : Controller
    {
        private readonly ICorsiService corsiService;

        public CorsiController(ICorsiService corsiService)
        {
            this.corsiService = corsiService;
        }
        public IActionResult Index()
        {
            ViewData["Title"] = "Catalogo dei corsi";
            List<CorsiViewModel> corsi = corsiService.GetCorsi();
            return View(corsi);
        }

        public IActionResult Detail(int id)
        {
            CorsiDetailViewModel viewModel = corsiService.GetCorso(id);
            ViewData["Title"] = viewModel.Title;
            return View(viewModel);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyCourse.Controllers
{
    public class HomeController : Controller
    {
        
        public IActionResult Index()
        {
            //return Content("Ciao");
            return View();
        }
    }
}

Views/Corsi/Detail.cshtml
@model CorsiDetailViewModel
<section class="course-info">
    <div class="row">
        <div class="col-md-9">
            <h1>@Model.Title</h1>
        </div>
        <div class="col-md-3 d-flex align-items-end">
            <a href="#" class="btn btn-warning btn-lg btn-block subscribe-course">Iscriviti</a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9">
            <p>@Model.Description</p>
        </div>
        <div class="col-md-3">
            <aside>
                <author>di @Model.Author</author>
                <div class="rating">
                   @for(int i = 1; i <= 5; i++)
        {
            if (Model.Rating >= i) 
            {
                <i class="fas far fa-star"></i>
            }
            else if (Model.Rating > i - 1)
            {
                <i class="fas fas fa-star-half-alt"></i>
            }
            else 
            {
                <i class="far fa-star"></i>
            }
        }
                </div>
                <div class="price">
                 @Model.CurrentPrice
                 @if(!@Model.CurrentPrice.Equals(Model.FullPrice))
                 {
                   <br><s>@Model.FullPrice</s>
                 }
                </div>
                <img src="~/logo.svg" class="img-fluid course-image" alt="Titolo del corso">
            </aside>
        </div>
    </div>
</section>

<section class="course-lessons">
	<h2>Lezioni (@Model.Lessons.Count)</h2>
	@foreach (var lesson in Model.Lessons)
	{
	<hr>
	<div class="row">
		<div class="col-md-9 d-flex align-items-center">
		    <a href="#">@lesson.Title</a>
		</div>
		<div class="col-md-3 d-flex align-items-center lesson-duration">
			<i class="far fa-clock"></i><time>@lesson.Duration.ToString("m'm 's's'")</time>
		</div>
	</div>
	}
    <hr>
    <div class="row course-duration">
		<div class="col-md-9 d-flex align-items-center">
            Totale
        </div>
        <div class="col-md-3 d-flex align-items-center">
            <i class="far fa-clock"></i><time>@Model.TotalCourseDuration.ToString("m'm 's's'")</time>
        </div>
    </div>
</section>

Views/Corsi/Index.cshtml
@model List<CorsiViewModel>
<h1>@ViewData["Title"]</h1>    


@foreach(CorsiViewModel corsi in Model)
{
<div class="row course">
    <div class="col-md-1">
        <img src="@corsi.ImagePath" width="52" height="52">
    </div>
    <div class="col-md-5">
        <h5 class="title">@corsi.Title</h5>
        <author>di @corsi.Author</author>
    </div>
    <div class="col-md-2 rating" Title="@corsi.Rating">
        @for(int i = 1; i <= 5; i++)
        {
            if (corsi.Rating >= i) 
            {
                <i class="fas far fa-star"></i>
            }
            else if (corsi.Rating > i - 1)
            {
                <i class="fas fas fa-star-half-alt"></i>
            }
            else 
            {
                <i class="far fa-star"></i>
            }
        }
    </div>
    <div class="col-md-2">
        @corsi.CurrentPrice
        @if(!@corsi.CurrentPrice.Equals(corsi.FullPrice))
        {
            <br><s>@corsi.FullPrice</s>
        }
    </div>
    <div class="col-md-2">
        <a class="btn btn-outline-primary" asp-action="Detail" asp-route-id="@corsi.Id">Dettaglio</a>
    </div>
</div>
<hr>

}

Views/Home/Index.cshtml
<h1>Benvenuto in myCourseeee</h1>    
<p>Lorem ipsum percge pensiamo di andare pazzescodolor sit amet consectetur adipisicing elit. Id tempore omnis molestias tempora assumenda aut quisquam, ipsa ullam ex repellat quidem eum nulla reprehenderit corporis facere vero ducimus esse non.</p>
<p>Quaerat, quibusdam percge pensiamo di andare pazzescout, qui non natus nam nobis eum saepe laudantium similique culpa sint eius corrupti est! Magni beatae cum quas id omnis iste est quam, neque minus ipsum error.</p>
<p>Nisi iste aliquam percge pensiamo di andare pazzescovoluptates hic rem aliquid unde aut voluptatem consectetur nulla necessitatibus suscipit sit sequi, libero fuga exercitationem. Placeat aspernatur consequuntur ullam, dolores repellat repudiandae amet deserunt possimus laboriosam?</p>
<p>Iste est laborum percge pensiamo di andare pazzescoconsequuntur quo velit accusamus dignissimos rerum nobis excepturi hic dolorem beatae temporibus nostrum corrupti quidem suscipit et, exercitationem cum non facilis repellendus eius eaque. Ut, earum eaque.</p>
<p>Quod nihil percge pensiamo di andare pazzescoea delectus animi consectetur voluptate asperiores fuga alias accusamus rem, obcaecati nesciunt cumque veniam ducimus quos praesentium perferendis soluta fugit mollitia, veritatis enim corporis? Obcaecati, cupiditate. Adipisci, deleniti.</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"]</title>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    </environment>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css">
    </environment>
    <link rel="stylesheet" href="~/style.css">
</head>
<body>
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand"><img src="~/logo.svg" height="30" alt="Logo MyCourse"></a>
    <button class="navbar-toggler" data-target="#navbar" data-toggle="collapse" aria-controls="my-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbar" class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-controller="Home">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-action="Index" asp-controller="Corsi" tabindex="-1" aria-disabled="true">Catalogo corsi</a>
            </li>
        </ul>
    </div>
</nav>
</header>

<div class="container">
@RenderBody()    
</div>


<footer>
    <p>Contattaci al numero...</p>
</footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.slim.min.js"></script>
        <script src="~/lib/popper/dist/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    </environment>
</body>
</html>